---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: stores.database.laf.dev
spec:
  group: database.laf.dev
  names:
    kind: Store
    listKind: StoreList
    plural: stores
    singular: store
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Store is the Schema for the stores API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: StoreSpec defines the desired state of Store
            properties:
              capacity:
                description: The capacity of the store.
                properties:
                  collectionCount:
                    default: 0
                    description: The number of collections. The default value is 0
                      which means unlimited.
                    format: int64
                    minimum: 0
                    type: integer
                  databaseCount:
                    default: 0
                    description: The number of databases. The default value is 0 which
                      means unlimited.
                    format: int64
                    minimum: 0
                    type: integer
                  storage:
                    anyOf:
                    - type: integer
                    - type: string
                    description: The storage space.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  userCount:
                    description: The user count of a store.
                    format: int64
                    type: integer
                type: object
              connectionURI:
                description: The connection uri of the store.
                type: string
              priority:
                default: 10
                description: Priority of the store. The higher the priority, the first
                  to be selected. If this value is 0, this store will not be selected
                  for allocating new database.
                format: int32
                maximum: 100
                minimum: 0
                type: integer
              provider:
                default: mongodb
                description: The provider of the store, defaults to "mongodb".
                maxLength: 64
                minLength: 2
                type: string
              region:
                default: default
                description: The region of the store, defaults to "default".
                maxLength: 64
                minLength: 2
                pattern: ^[a-z0-9-]+$
                type: string
            required:
            - connectionURI
            - provider
            - region
            type: object
          status:
            description: StoreStatus defines the observed state of Store
            properties:
              capacity:
                description: The observed capacity of the store.
                properties:
                  collectionCount:
                    default: 0
                    description: The number of collections. The default value is 0
                      which means unlimited.
                    format: int64
                    minimum: 0
                    type: integer
                  databaseCount:
                    default: 0
                    description: The number of databases. The default value is 0 which
                      means unlimited.
                    format: int64
                    minimum: 0
                    type: integer
                  storage:
                    anyOf:
                    - type: integer
                    - type: string
                    description: The storage space.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  userCount:
                    description: The user count of a store.
                    format: int64
                    type: integer
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
