---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: databases.database.laf.dev
spec:
  group: database.laf.dev
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Database is the Schema for the databases API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DatabaseSpec defines the desired state of Database
            properties:
              capacity:
                description: Capacity desired.
                properties:
                  storage:
                    anyOf:
                    - type: integer
                    - type: string
                    description: The storage space of database.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                type: object
              password:
                description: Password of the database.
                maxLength: 32
                minLength: 16
                type: string
              provider:
                description: Provider name of the database. The controller will create
                  the corresponding storage resources based on this provider.
                type: string
              username:
                description: Username of the database.
                maxLength: 16
                minLength: 6
                type: string
            required:
            - capacity
            - password
            - provider
            - username
            type: object
          status:
            description: DatabaseStatus defines the observed state of Database
            properties:
              capacity:
                description: Capacity observed by the controller
                properties:
                  storage:
                    anyOf:
                    - type: integer
                    - type: string
                    description: The storage space of database.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                type: object
              connectionURI:
                description: ConnectionURI of the database.
                type: string
              store:
                description: Store name of this database. The controller has created
                  the corresponding storage resources based on this store.
                type: string
              storeNamespace:
                type: string
            required:
            - connectionURI
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
