---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: instances.instance.laf.dev
spec:
  group: instance.laf.dev
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    shortNames:
    - instance
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.region
      name: REGION
      type: string
    - jsonPath: .status.status
      name: STATUS
      type: string
    - jsonPath: .status.readyReplicas
      name: READY
      type: string
    - jsonPath: .status.updatedReplicas
      name: UP-TO-DATE
      type: string
    - jsonPath: .status.availableReplicas
      name: AVAILABLE
      type: string
    - jsonPath: .status.unavailableReplicas
      name: UNAVAILABLE
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Instance is the Schema for the instances API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: InstanceSpec defines the desired state of Instance
            properties:
              appid:
                description: AppId of the instance
                type: string
              bundle:
                description: Bundle of the instance
                properties:
                  databaseCapacity:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Database capacity for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  displayName:
                    description: DisplayName for the bundle
                    type: string
                  limitCPU:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Limit CPU for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  limitMemory:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Limit Memory for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  networkBandwidthInbound:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Network Bandwidth Inbound for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  networkBandwidthOutbound:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Network Bandwidth Outbound for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  networkTrafficOutbound:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Network Traffic Outbound for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  requestCPU:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Request CPU for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  requestMemory:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Request Memory for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  storageCapacity:
                    anyOf:
                    - type: integer
                    - type: string
                    description: Storage capacity for the bundle
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                required:
                - databaseCapacity
                - displayName
                - limitCPU
                - limitMemory
                - networkTrafficOutbound
                - requestCPU
                - requestMemory
                - storageCapacity
                type: object
              databaseConnectionUri:
                description: Database of the instance
                type: string
              ossUser:
                description: OssAccess of the instance
                properties:
                  accessKey:
                    description: AccessKey is the access key of the user
                    type: string
                  endpoint:
                    description: Endpoint is the oss server endpoint.
                    type: string
                  internalEndpoint:
                    description: InternalEndpoint is the internal endpoint of the
                      oss server
                    type: string
                  region:
                    description: Region of oss store.
                    type: string
                  secretKey:
                    description: SecretKey is the secret key of the user
                    type: string
                required:
                - region
                type: object
              replica:
                default: 1
                description: Replica of instance
                format: int32
                type: integer
              runtime:
                description: Runtime of the instance
                properties:
                  image:
                    description: Images of the runtime
                    properties:
                      init:
                        description: Init image (e.g. docker.io/lafyun/app-service-init:latest)
                        type: string
                      main:
                        description: Main image (e.g. docker.io/lafyun/app-service:latest)
                        type: string
                      sidecar:
                        description: Sidecar image
                        type: string
                    required:
                    - main
                    type: object
                  latest:
                    description: Latest version or not
                    type: boolean
                  name:
                    type: string
                  type:
                    description: Type of the runtime. eg. node:laf, node:tcb, go:laf,
                      python:laf, php:laf,  etc.
                    type: string
                  version:
                    description: Version of the runtime
                    type: string
                required:
                - image
                - name
                - type
                - version
                type: object
              state:
                description: State of the instance
                enum:
                - Running
                - Stopped
                type: string
            type: object
          status:
            description: InstanceStatus defines the observed state of Instance
            properties:
              DeploymentName:
                type: string
              availableReplicas:
                description: Total number of available pods (ready for at least minReadySeconds)
                  targeted by this deployment.
                format: int32
                type: integer
              conditions:
                description: Conditions of the instance @see string for the list of
                  conditions
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    \n type FooStatus struct{ // Represents the observations of a
                    foo's current state. // Known .status.conditions.type are: \"Available\",
                    \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge
                    // +listType=map // +listMapKey=type Conditions []metav1.Condition
                    `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\"
                    protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers
                        of specific condition types may define expected values and
                        meanings for this field, and whether the values are considered
                        a guaranteed API. The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              readyReplicas:
                description: readyReplicas is the number of pods targeted by this
                  Deployment with a Ready Condition.
                format: int32
                type: integer
              replicas:
                format: int32
                type: integer
              serviceName:
                type: string
              status:
                type: string
              unavailableReplicas:
                description: Total number of unavailable pods targeted by this deployment.
                  This is the total number of pods that are still required for the
                  deployment to have 100% available capacity. They may either be pods
                  that are running but not yet available or pods that still have not
                  been created.
                format: int32
                type: integer
              updatedReplicas:
                description: Total number of non-terminated pods targeted by this
                  deployment that have the desired template spec.
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
