# permissions for end users to view functions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: function-viewer-role
rules:
- apiGroups:
  - runtime.laf.dev
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtime.laf.dev
  resources:
  - functions/status
  verbs:
  - get
