# permissions for end users to view databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-viewer-role
rules:
- apiGroups:
  - database.database.laf.dev
  resources:
  - databases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.database.laf.dev
  resources:
  - databases/status
  verbs:
  - get
