### Databases configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: laf
data:
  sys-db-uri: "mongodb://my_user:password123@mongo.laf:27017/sys_db?authSource=sys_db&replicaSet=laf&writeConcern=majority"
  app-db-uri: "mongodb://root:password123@mongo.laf:27017/?authSource=admin&replicaSet=laf&writeConcern=majority&maxPoolSize=10"

### OSS configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oss-config
  namespace: laf
data:
  minio-root-user: "minio-root-user"
  minio-root-password: "minio-root-password"
  minio-region-name: "cn-default"
  minio-domain: "oss.127-0-0-1.nip.io"
  internal-endpoint: "http://oss:9000"
  external-endpoint: "http://oss.127-0-0-1.nip.io"


### Root account for system extension app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: root-account
  namespace: laf
data:
  account: "root"
  password: "abc123"

### Server secrets used for signature tokens
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-salt
  namespace: laf
data:
  system-server-salt: "Rewrite_Your_Own_Secret_Salt_abcdefg1234567"

### Deployment domains for gateway & clients
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-domain
  namespace: laf
data:
  app-service-host: "127-0-0-1.nip.io" # `*.127-0-0-1.nip.io` always resolved to 127.0.0.1, used to local development
  deploy-url-schema: "http"

### App service config & default quotas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-service
  namespace: laf
data:
  image: "docker.io/lafyun/app-service:0.8.0-alpha.9"
  default-app-quota-created-per-user: "5"
  account-signup-mode: "0"
  kube-namespace-of-app-services: 'laf-apps'
  system-appid: "000000"
  appid-length: "6"
